### ISSUE TITLE
LoL funny boy delete this repo if u dont wanna DMCA takedown

### ISSUE THREAD

**Issue by 0x24a** [ying145114/xc-dynobot-#2]
> 你好，我想跟你说。如果你访问了这个仓库，那么请不要删除压缩包。 如果你删除了，那么你会后果自负。 你可以下载，但不要删除。 你没有权利去上传新的文件，否则你将会受到惩罚。 如果你犯了其中一条，那么请自备一份检讨书发送到:[adxin1@outlook.com](mailto:adxin1@outlook.com) 2022.12.2.星期五晚20:32编写

不是你以为你算老几啊 直接给你账号DMCA Takedown了行吧

**Comment by MrZhang365** [comment]
lol
